# Postgres SQL configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planningpoker_db
    username: postgres
    password: devjack@@tech
    driver-class-name: org.postgresql.Driver

  # Postgres SQL dialect configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Server port configuration
server:
  port: 8080

# Spring profile
profiles:
  active: dev

# Log configuration
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
